### ISSUE TITLE
[FEAT] Add an example of a project using Angular

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bpmn-visualization-examples#20]
Use Angular 14 with TypeScript
Store the project in a subfolder of the `projects` directory.

This issue is for the first implementation. For later improvements, see #409

**Comment by akantcheff** [comment]
Hello! I can take a look on this one :)

**Comment by tbouffard** [comment]
> Hello! I can take a look on this one :)

Great, go for it!
