### ISSUE TITLE
[BUG] docs: using mxGraph in extensions requires mxGraph typings.

### ISSUE THREAD

**Issue by kristapsdz-saic** [process-analytics/bpmn-visualization-examples#294]
**Describe the bug**
Without specifying the @typed-mxgraph/typed-mxgraph package in one's *tsconfig.json*, building with mxGraph extensions will fail, as it cannot find types.  This should be noted in the documentation.

**To Reproduce**

A simple example:
```
import { BpmnVisualization, ShapeBpmnElementKind} from 'bpmn-visualization';
export class BPMNVisualiser extends BpmnVisualization {
        constructor(id: string) {
                super({ container: id });
                this.configureStyle();
        }
        private configureStyle(): void {
                const styleSheet = this.graph.getStylesheet();
                const style = styleSheet.styles[ShapeBpmnElementKind.TASK_SERVICE];
                style['fontColor'] = '#2b992a';
        }
}
```
The `tsc` compiler errors out:
```
node_modules/bpmn-visualization/dist/component/mxgraph/initializer.d.ts(1,23): error TS2688: Cannot find type definition file for 'typed-mxgraph'.
node_modules/bpmn-visualization/dist/component/mxgraph/initializer.d.ts(17,42): error TS7016: Could not find a declaration file for module 'mxgraph'. '/.../node_modules/bpmn-visualization/node_modules/mxgraph/javascript/dist/build.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/mxgraph` if it exists or add a new declaration (.d.ts) file containing `declare module 'mxgraph';`
node_modules/bpmn-visualization/dist/component/mxgraph/shape/render/BpmnCanvas.d.ts(16,23): error TS2688: Cannot find type definition file for 'typed-mxgraph'.
node_modules/bpmn-visualization/dist/component/mxgraph/shape/render/BpmnCanvas.d.ts(18,41): error TS7016: Could not find a declaration file for module 'mxgraph'. '/.../node_modules/bpmn-visualization/node_modules/mxgraph/javascript/dist/build.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/mxgraph` if it exists or add a new declaration (.d.ts) file containing `declare module 'mxgraph';`
node_modules/bpmn-visualization/dist/component/mxgraph/shape/render/icon-painter.d.ts(16,23): error TS2688: Cannot find type definition file for 'typed-mxgraph'.
node_modules/bpmn-visualization/dist/component/mxgraph/shape/render/icon-painter.d.ts(19,41): error TS7016: Could not find a declaration file for module 'mxgraph'. '/.../node_modules/bpmn-visualization/node_modules/mxgraph/javascript/dist/build.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/mxgraph` if it exists or add a new declaration (.d.ts) file containing `declare module 'mxgraph';`
src/typescript/BPMNVisualiser.ts(17,33): error TS2339: Property 'getStylesheet' does not exist on type 'BpmnGraph'.
```

To fix this, one needs to install the mxGraph typings:

```
npm install @typed-mxgraph/typed-mxgraph
```

Then modify one's *tsconfig.json* to include the following:

```
{
  "compilerOptions": {
    "target": "es6",
    "moduleResolution": "node",
    "noEmitOnError": true,
    "lib": [
      "es6",
      "dom"
    ],
    "strict": true,
    "outDir": "./build",
    "rootDir": "src/typescript",
    "typeRoots": [
      "node_modules/@types",
      "node_modules/@typed-mxgraph"
    ]
  }
}
```
At this point it works beautifully!

**Additional context**
Both the current `0.21.5` and older `0.21.2` were affected and fixed by this.

**Comment by tbouffard** [comment]
Hello @kristapsdz-saic and thanks for the report.

The `bpmn-visualization` README was updated in v0.21.5 to better explain how to integrate the library in a TypeScript project: https://github.com/process-analytics/bpmn-visualization-js/tree/v0.21.5#typescript-support. It also contains an explicit statement about the mxGraph integration
> Advanced users that want to extend the mxGraph integration must configure typed-mxgraph.

Isn't that enough?
In the README of the examples repostiory, I could add a link to the library README as a reminder for TypeScript users.

**Comment by kristapsdz-saic** [comment]
Thanks again for getting to this so soon!  I would either put a link or just drop the @typed-mxgraph requirements on the examples themselves, e.g., https://github.com/process-analytics/bpmn-visualization-examples/blob/master/examples/custom-bpmn-theme/custom-fonts/README.md  But this is my fault, as I didn't read the README.md you linked close enough, so feel free to close this out as-is.

In a related note, the mxConstants strings are undefined if the examples are used directly: in my example above, I directly used `fontColor` instead of digging around to see how to initialise the mxGraph bits.  However, I assume this is part of "mxGraph knowledge is required", so am not reporting it.

**Comment by tbouffard** [comment]
@kristapsdz-saic I have created #295 to provide more guidance in the README of the examples repository. Feel free to provide feedback.

About `mxConstants`, it may be possible to use it in projects but this would require to run some mxGraph settings code because `bpmn-visualization` doesn't expose the `mxGraph` object values for now (we aren't sure we want to make them public in the future).
Using string constants as you did for `fontColor` is the right way (or introducing constants in your code), so the README files mentioning `mxConstants` should be updated to remove such references. Thanks for noticing it.
I will let you know when the change is available.

**Comment by kristapsdz-saic** [comment]
These pulls fix all of the nits I noticed.  Thank you so much! :)
