### ISSUE TITLE
[BUG] The back to top button in the example HTML home page doesn't display anymore on Firefox

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bpmn-visualization-examples#373]
**Describe the bug**
The button that is supposed to display on top right of the page when user scroll down doesn't display anymore.
This seems not related to the latest v0.26.0. I also see this with v0.25.2 or v0.21.0 (and potentially with all versions)

**To Reproduce**
1. Go to https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/v0.26.0/examples/index.html#bpmn-rendering
2. See error: the button doesn't display

**Screenshots**

Expected | Current
---- | ----
![image](https://user-images.githubusercontent.com/27200110/185939756-8d899645-0f50-4ef4-8cf6-da1b912ea520.png) | ![image](https://user-images.githubusercontent.com/27200110/185939274-9d73561d-4743-4919-a211-464b6df40bed.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS
 - Browser [e.g. chrome, safari]: Firefox
 - Version [e.g. 22]: 103.0 (64 bits)

**Additional context**
Work on Chrome 104.0.5112.101 (64 bits).
I see new traces in the Firefox dev tools console from statically.io. Probably not related, but I detected theme at the same time as the not displayed button
I don't see such traces with Chrome
```
15:55:55,758 statically.io#%#//scriptlet('set-constant', 'Document.prototype.browsingTopics', 'undefined') trace start index.html:206:16
15:55:55,759 console.trace() index.html:208:15
    hit https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/v0.26.0/examples/index.html:208
    setChainPropAccess https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/v0.26.0/examples/index.html:166
    setConstant https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/v0.26.0/examples/index.html:176
    <anonyme> https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/v0.26.0/examples/index.html:305
    <anonyme> https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/v0.26.0/examples/index.html:310
    <anonyme> https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/v0.26.0/examples/index.html:317
15:55:55,759 statically.io#%#//scriptlet('set-constant', 'Document.prototype.browsingTopics', 'undefined') trace end index.html:210:16
```

⚠️  Tested locally without dev server: the button displays. It may be a statically.io integration issue.

**Comment by csouchet** [comment]
### On macOS

Tested with https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/v0.26.0/examples/index.html#bpmn-rendering

#### Firefox 103.0.2 (64 bits)

No problem and no error on console.

<img width="1663" alt="image" src="https://user-images.githubusercontent.com/4921914/186151997-68fd3097-d5f2-411a-9fc3-f92d9404a81b.png">


#### Safari 15.6 (17613.3.9.1.5)

No problem and no error on console.

<img width="1663" alt="image" src="https://user-images.githubusercontent.com/4921914/186152296-6f9eb2a7-cad1-40af-aebb-4f6a14f4eeb1.png">


#### Chrome

No problem and no error on console.

<img width="1663" alt="image" src="https://user-images.githubusercontent.com/4921914/186152639-8214de1d-f3b7-4d01-8adb-40576c358361.png">

**Comment by tbouffard** [comment]
I have just understood what was my problem. What I see is due to the [Qwant VIPrivacy extension](https://github.com/Qwant/qwant-viprivacy#readme). I see the button when I disable the extension.
The extension I use is version `7.0.5`.

This is also this extension that generates the trace log in the DevTools console. I also see the traces on surge deployments like 👇🏿 
```
14:19:18,654 surge.sh#%#//scriptlet('set-constant', 'Document.prototype.browsingTopics', 'undefined') trace start [process-analytics-process-analytics-dev-site_preview-pr-604.surge.sh:206:16](https://process-analytics-process-analytics-dev-site_preview-pr-604.surge.sh/)
14:19:18,656 console.trace() [process-analytics-process-analytics-dev-site_preview-pr-604.surge.sh:208:15](https://process-analytics-process-analytics-dev-site_preview-pr-604.surge.sh/)
    hit https://process-analytics-process-analytics-dev-site_preview-pr-604.surge.sh/:208
    setChainPropAccess https://process-analytics-process-analytics-dev-site_preview-pr-604.surge.sh/:166
    setConstant https://process-analytics-process-analytics-dev-site_preview-pr-604.surge.sh/:176
    <anonyme> https://process-analytics-process-analytics-dev-site_preview-pr-604.surge.sh/:305
    <anonyme> https://process-analytics-process-analytics-dev-site_preview-pr-604.surge.sh/:310
    <anonyme> https://process-analytics-process-analytics-dev-site_preview-pr-604.surge.sh/:317
14:19:18,656 surge.sh#%#//scriptlet('set-constant', 'Document.prototype.browsingTopics', 'undefined') trace end
```

As this is an local environment issue, I am closing this issue.
