### ISSUE TITLE
[FEAT] Use SVG favicon instead of PNG

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bpmn-visualization-examples#376]
**Is your feature request related to a problem? Please describe.**
This is something that we already do in the ViteJS TS project and in bpmn-visualization (see https://github.com/process-analytics/bpmn-visualization-js/pull/2175)
For consistency and to improve the favicon quality

**Describe the solution you'd like**
To be done in 
- examples
- demo
- projects

**Additional context**
At least in projects, simplify the layout of directories that store assets. We don't need to have so many sub-directories.

**Comment by educhastenier** [comment]
Hello! I'd like to contribute on this issue.
