### ISSUE TITLE
Contributing as part of Hacktoberfest 2022!

### ISSUE THREAD

**Issue by assynour** [process-analytics/bpmn-visualization-examples#402]
![hacktoberfest 2022 hero image](https://user-images.githubusercontent.com/27200110/191725941-8981e2e5-7309-4cf6-99f6-1bea1f926b06.jpg)

**You're one step away of starting your contribution and becoming our HacktoberHero :heart_eyes:**

Before you start, check out our [article](https://medium.com/@process-analytics/hacktoberfest-2022-with-process-analytics-add185b50721) and please follow these rules:

1. Choose any issue labeled with https://github.com/process-analytics/bpmn-visualization-examples/labels/hacktoberfest.
2. Add a **comment :pencil2:** on the chosen issue to express your desire to work on it. In principle, the issue should not be assigned to someone else. We will try to respond to you as quickly as possible, to give you any required information and to assign you the issue.
3. Please **commit :pushpin:** to the assigned issue, and in case of unavoidable change, let us know as early as possible.
4. **Read carefully :scroll:** the issue description and follow the general [contribution guidelines](../blob/master/CONTRIBUTING.md), in addition to any specific guideline mentioned in the issue. In any doubt, contact us directly via Github or on our [discord channel](https://discord.gg/32azxj6bNf).
5. Once done, create your **PR request :fire:** and 🤞

**Comment by tbouffard** [comment]
Hacktoberfest 2022 is over, see you next year!
