### ISSUE TITLE
[BUG] Fix the impact of the BpmnSemantic in examples when integrating bpmn-visualization 0.41.0

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bpmn-visualization-examples#549]
https://github.com/process-analytics/bpmn-visualization-js/pull/2854 introduces several new properties.
The `javascript-tooltip-and-popover` example displaying BpmnSemantic information should be reviewed to see if properties display correctly (if applicable) 
The order of properties may be reworked.

**Comment by tbouffard** [comment]
❌ Check with https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/v0.41.0/examples/custom-behavior/javascript-tooltip-and-popover/index.html

Before | After
---- | ----
![before](https://github.com/process-analytics/bpmn-visualization-examples/assets/27200110/28c37911-8829-4a54-b493-e4b0d6a9aa43) | ![after](https://github.com/process-analytics/bpmn-visualization-examples/assets/27200110/2e99f361-17e8-4eed-87f9-4e4756a9026e)

**Comment by csouchet** [comment]
I don't see why that's a problem, since that's what we wanted to display in the first place, but I don't mind not displaying them anymore :slightly\_smiling\_face:

**Comment by tbouffard** [comment]
> I don't see why that's a problem, since that's what we wanted to display in the first place, but I don't mind not displaying them anymore 🙂

Some popovers are too large so some information is not visible whereas properties without data are displayed.
This is what I tried to explain in https://github.com/process-analytics/bpmn-visualization-examples/issues/549#issuecomment-1745327013
