### ISSUE TITLE
Contributing as part of Hacktoberfest 2023!

### ISSUE THREAD

**Issue by assynour** [process-analytics/bpmn-visualization-examples#562]
![hacktoberfest2023](https://github.com/process-analytics/bpmn-visualization-js/assets/67027776/81d3767d-1c97-45ba-bc94-de2ecc5627e3)

**You're one step away of starting your contribution and becoming our HacktoberHero :heart_eyes:**

Before you start, please follow these rules:

1. Make sure that you've registered to [Hacktoberfest 2023](https://hacktoberfest.com/auth/).
2. Choose any issue labeled with https://github.com/process-analytics/bpmn-visualization-examples/labels/hacktoberfest.
3. Add a **comment :pencil2:** on the chosen issue to express your desire to work on it. In principle, the issue should not be assigned to someone else. We will try to respond to you as quickly as possible, to give you any required information and to assign you the issue.
4. Please **commit :pushpin:** to the assigned issue, and in case of unavoidable change, let us know as early as possible.
5. **Read carefully :scroll:** the issue description and follow the general [contribution guidelines](../blob/master/CONTRIBUTING.md), in addition to any specific guideline mentioned in the issue. In any doubt, contact us directly via Github or on our [discord channel](https://discord.gg/32azxj6bNf).
6. Once done, create your **PR request :fire:** and 🤞

**Comment by tbouffard** [comment]
The Hacktoberfest event is over, so closing this issue.
